server:
  appname: modx-test
  description: MODX test server
  version: 1.0.0
  debug: true

cache:
  split: ':'
  pref: 'modx:'
  redis:
    host: localhost
    port: 6379
    db: 0
    password: null
